-- MySQL Script generated by MySQL Workbench
-- Tue 11 Nov 2014 03:00:00 AM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `Person_id` INT NOT NULL AUTO_INCREMENT,
  `Person_first_name` VARCHAR(45) NULL,
  `Person_last_name` VARCHAR(45) NULL,
  `Person_zip` VARCHAR(45) NULL,
  `Person_address` VARCHAR(100) NULL,
  `Person_state` VARCHAR(45) NULL,
  `Person_city` VARCHAR(45) NULL,
  `Person_ssn` CHAR(9) NULL,
  `Person_email` VARCHAR(45) NULL,
  `Person_pass` VARCHAR(45) NULL,
  PRIMARY KEY (`Person_id`),
  UNIQUE INDEX `Person_email_UNIQUE` (`Person_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seller` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seller` (
  `Seller_id` INT NOT NULL AUTO_INCREMENT,
  `Person_id` INT NULL,
  `Seller_rate` INT NULL,
  PRIMARY KEY (`Seller_id`),
  INDEX `fk_Seller_1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Seller_1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`Person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_id` INT NOT NULL AUTO_INCREMENT,
  `Person_id` INT NULL,
  PRIMARY KEY (`Customer_id`),
  INDEX `fk_Buyer_1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Buyer_1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`Person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Category_id` INT NOT NULL AUTO_INCREMENT,
  `Categorycol` VARCHAR(45) NULL,
  PRIMARY KEY (`Category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_id` INT NOT NULL AUTO_INCREMENT,
  `Product_name` VARCHAR(45) NULL,
  `Product_category_id` INT NULL,
  `Product_price` VARCHAR(45) NULL,
  `Product_condition` TINYINT(1) NULL DEFAULT 0,
  `Product_type` INT NULL DEFAULT 0 COMMENT 'condition is new/used\ntype is bid/sell/bid&sell',
  `Product_seller_id` INT NULL,
  `Product_info` VARCHAR(45) NULL,
  PRIMARY KEY (`Product_id`),
  INDEX `fk_Product_1_idx` (`Product_seller_id` ASC),
  INDEX `fk_Product_2_idx` (`Product_category_id` ASC),
  CONSTRAINT `fk_Product_1`
    FOREIGN KEY (`Product_seller_id`)
    REFERENCES `mydb`.`Seller` (`Seller_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_2`
    FOREIGN KEY (`Product_category_id`)
    REFERENCES `mydb`.`Category` (`Category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TransHistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TransHistory` (
  `TransHistory_id` INT NOT NULL AUTO_INCREMENT,
  `TransHistory_Buyer_id` INT NULL,
  `TransHistory_Seller_id` INT NULL,
  `TransHistory_Product_id` INT NULL,
  `TransHistory_time` TIMESTAMP NULL,
  `TransHistory_type` CHAR NULL,
  PRIMARY KEY (`TransHistory_id`),
  INDEX `fk_TransHistory_1_idx` (`TransHistory_Buyer_id` ASC),
  INDEX `fk_TransHistory_2_idx` (`TransHistory_Seller_id` ASC),
  INDEX `fk_TransHistory_3_idx` (`TransHistory_Product_id` ASC),
  CONSTRAINT `fk_TransHistory_1`
    FOREIGN KEY (`TransHistory_Buyer_id`)
    REFERENCES `mydb`.`Customer` (`Customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TransHistory_2`
    FOREIGN KEY (`TransHistory_Seller_id`)
    REFERENCES `mydb`.`Seller` (`Seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TransHistory_3`
    FOREIGN KEY (`TransHistory_Product_id`)
    REFERENCES `mydb`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;